### ISSUE TITLE
Schedule task list

### ISSUE THREAD

**Issue by rthor** [jsis/jsconf.is#95]
## Task list:

- [x] Navigate between talks with arrow keys.
- [x] Save your favorite talks _(localStorage implementation)_
- [x] Images of speakers

## What I want to get finished before the conference starts (but will probably  not):

- [ ] Offline support.
- [ ] Notify when favorite talks are starting - push notification.
- [ ] Indicate current talk in the schedule. See attached mock image.

## Other nice to have ideas:

- [ ] Format a printable version of the schedule and add a "Print" button.
- [ ] Download schedule to your calendar. The only problem is formatting correctly, should be relatively easy though.
- [ ] Send to device - simple way of sharing the favorite talk state. Just create a QR code and scan it on your mobile phone f.ex.
- [ ] Night / day theme switching.
- [ ] We should add support for arbitrary "files and links" section for each talk. So when it's over we can add slides, youtube link, and other mentioned URLs.
- [ ] Rewrite the entire schedule 🤡 But seriously, we shouldn't.

## Attachment
![screen shot 2018-02-25 at 01 53 37](https://user-images.githubusercontent.com/1608329/36637201-bccfc658-19ce-11e8-8cdc-92b6b706b8cc.png)
